# Project: encrypter
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = encrypter.o main.o
LINKOBJ  = encrypter.o main.o
LIBS     = -L"H:/Dev-Cpp/MinGW64/lib" -L"H:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib"
INCS     = -I"H:/Dev-Cpp/MinGW64/include" -I"H:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"H:/Dev-Cpp/MinGW64/include" -I"H:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"H:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = encrypter.exe
CXXFLAGS = $(CXXINCS) -std=c++14
CFLAGS   = $(INCS) -std=c++14
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

encrypter.o: encrypter.cpp
	$(CPP) -c encrypter.cpp -o encrypter.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
